# Form implementation generated from reading ui file 'dichVu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 676)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 401, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 110, 781, 171))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txtName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtName.setGeometry(QtCore.QRect(140, 40, 221, 22))
        self.txtName.setObjectName("txtName")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 55, 21))
        self.label_3.setObjectName("label_3")
        self.cbGender = QtWidgets.QComboBox(parent=self.groupBox)
        self.cbGender.setGeometry(QtCore.QRect(140, 70, 91, 21))
        self.cbGender.setObjectName("cbGender")
        self.cbGender.addItem("")
        self.cbGender.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 300, 781, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBoxCafe = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBoxCafe.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.checkBoxCafe.setObjectName("checkBoxCafe")
        self.checkBoxBimBim = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBoxBimBim.setGeometry(QtCore.QRect(160, 20, 81, 20))
        self.checkBoxBimBim.setObjectName("checkBoxBimBim")
        self.spinBoxNguoiLon = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.spinBoxNguoiLon.setGeometry(QtCore.QRect(110, 70, 42, 22))
        self.spinBoxNguoiLon.setObjectName("spinBoxNguoiLon")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 55, 16))
        self.label_5.setObjectName("label_5")
        self.spinBoxTrem = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.spinBoxTrem.setGeometry(QtCore.QRect(110, 110, 42, 22))
        self.spinBoxTrem.setObjectName("spinBoxTrem")
        self.btnTinhTien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTinhTien.setGeometry(QtCore.QRect(90, 530, 93, 28))
        self.btnTinhTien.setObjectName("btnTinhTien")
        self.txtTienTra = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTienTra.setGeometry(QtCore.QRect(260, 530, 113, 22))
        self.txtTienTra.setObjectName("txtTienTra")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnTinhTien.clicked.connect(self.TinhTien)
    def TinhTien(self):
        
        self.txtTienTra.setText(self.txtName.text())
        msg = QtWidgets.QMessageBox()
        msg.setInformativeText(self.txtName.text())
        msg.exec()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ứng dụng bán vé"))
        self.groupBox.setTitle(_translate("MainWindow", "Thông tin khách hàng"))
        self.label_2.setText(_translate("MainWindow", "Họ tên"))
        self.label_3.setText(_translate("MainWindow", "Giới tính"))
        self.cbGender.setItemText(0, _translate("MainWindow", "Nam"))
        self.cbGender.setItemText(1, _translate("MainWindow", "Nu"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Dịch vụ"))
        self.checkBoxCafe.setText(_translate("MainWindow", "Cafe"))
        self.checkBoxBimBim.setText(_translate("MainWindow", "BimBim"))
        self.label_4.setText(_translate("MainWindow", "Người lớn"))
        self.label_5.setText(_translate("MainWindow", "Trẻ em"))
        self.btnTinhTien.setText(_translate("MainWindow", "Tiền trả"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
