# Form implementation generated from reading ui file 'ListView.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QTableView
from PyQt6.QtCore import QAbstractTableModel, Qt
class MyTableModel(QAbstractTableModel):
    def __init__(self, data, headers):
        super().__init__()
        self._data = data
        self._headers = headers

    def rowCount(self, parent):
        return len(self._data)

    def columnCount(self, parent):
        return len(self._headers)

    def data(self, index, role):
        if role == Qt.ItemDataRole.DisplayRole:
            row = index.row()
            col = index.column()
            return self._data[row][col]
        if role == Qt.ItemDataRole.CheckStateRole and index.column() == 0:
            # Trả về trạng thái checkbox dựa trên giá trị trong dòng đó
            if self._data[index.row()][0]:
                return Qt.CheckState
            # else:
            #     return Qt.CheckState.Unchecked

    def headerData(self, section, orientation, role):
        if role == Qt.ItemDataRole.DisplayRole:
            if orientation == Qt.Orientation.Horizontal:
                return self._headers[section]
            else:
                return f"Row {section + 1}"
    def setData(self, index, value, role):
        if role == Qt.ItemDataRole.CheckStateRole and index.column() == 0:
            # Cập nhật dữ liệu dựa trên trạng thái checkbox
            # if value == Qt.CheckState.Checked:
            #     self._data[index.row()][0] = True
            # else:
            #     self._data[index.row()][0] = False

            # Gửi tín hiệu dataChanged để cập nhật giao diện
            self.dataChanged.emit(index, index, [role])
            return True

        return False

    def flags(self, index):
        flags = super().flags(index)
        if index.column() == 0:
            flags |= Qt.ItemFlag.ItemIsUserCheckable
        return flags
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 826)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 461, 571))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_5.setObjectName("label_5")
        self.txt_khoa_can_chia_se = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_khoa_can_chia_se.setGeometry(QtCore.QRect(290, 40, 113, 22))
        self.txt_khoa_can_chia_se.setObjectName("txt_khoa_can_chia_se")
        self.txt_so_thanh_vien_giu_khoa = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_so_thanh_vien_giu_khoa.setGeometry(QtCore.QRect(290, 70, 113, 22))
        self.txt_so_thanh_vien_giu_khoa.setObjectName("txt_so_thanh_vien_giu_khoa")
        self.txt_so_thanh_vien_toi_thieu = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_so_thanh_vien_toi_thieu.setGeometry(QtCore.QRect(290, 110, 113, 22))
        self.txt_so_thanh_vien_toi_thieu.setObjectName("txt_so_thanh_vien_toi_thieu")
        self.txt_p = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_p.setGeometry(QtCore.QRect(290, 140, 113, 22))
        self.txt_p.setObjectName("txt_p")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 170, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        data = [
            ["John", 30, "Male"],
            ["Jane", 25, "Female"],
            ["Doe", 40, "Male"],
            ["Emily", 35, "Female"]
        ]
        headers = ["Name", "Age", "Gender"]
        self.table_model = MyTableModel(data, headers)
        self.tableView = QtWidgets.QTableView(parent=self.groupBox)
        self.tableView.setGeometry(QtCore.QRect(40, 260, 500, 192))
        self.tableView.setObjectName("tableView")
        self.tableView.setModel(self.table_model)
        self.tableView.verticalHeader().setVisible(False)
        #self.tableView.horizontalHeader().setSectionResizeMode(Qt.QHeaderView.ResizeMode.Stretch)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Chia khóa"))
        self.label_2.setText(_translate("MainWindow", "Số thành viên giữ khóa"))
        self.label_3.setText(_translate("MainWindow", "Khóa cần chia sẽ"))
        self.label_4.setText(_translate("MainWindow", "Số thành viên tối thiểu để mở khóa"))
        self.label_5.setText(_translate("MainWindow", "Giá trị p"))
        self.pushButton.setText(_translate("MainWindow", "Chia sẻ khóa"))
        self.pushButton_2.setText(_translate("MainWindow", "Nhập lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
